version: "3.9"

services:
  nexus:
    build: .
    container_name: nexus-autoforward
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./session:/app/session
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
